version: '3.8'

services:
  quarkus-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: quarkus-app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/q/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  grafana-agent:
    image: grafana/agent:latest
    volumes:
      - ./grafana-agent/agent.yaml:/etc/agent.yaml
    command: -config.file=/etc/agent.yaml
    container_name: grafana-agent
    depends_on:
      quarkus-app:
        condition: service_healthy
