name: CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Ambiente para o deploy'
        required: true
        default: 'des'
        type: choice
        options:
          - des
          - prd

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Clone do repositório
        uses: actions/checkout@v3

      - name: Configuração JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build Native executável com Maven
        run: |
          cd getting-started
          ./mvnw clean package -Pnative

      - name: Configuração Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login no DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build e Push da imagem Docker
        run: |
          cd getting-started
          # O nome do ambiente vem do input manual
          ENVIRONMENT_NAME="${{ github.event.inputs.environment }}"
          
          IMAGE_TAG=${{ secrets.DOCKER_USERNAME }}/quarkus-native:1.0-${ENVIRONMENT_NAME}
          docker build --no-cache --tag $IMAGE_TAG .
          docker push $IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
      
      - name: Deploy no Minikube
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MINIKUBE_IP }}
          username: ${{ secrets.MINIKUBE_USERNAME }}
          key: ${{ secrets.MINIKUBE_SSH_KEY }}
          script: |
            cd /home/tercioga/project/devsecops-hackathoncaixa
            ENVIRONMENT_NAME="${{ github.event.inputs.environment }}"
            sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/quarkus-native:1.0-${ENVIRONMENT_NAME}|" kubernetes/base/deployment.yaml

            kubectl apply -k kubernetes/$ENVIRONMENT_NAME
